classmail: default config preparation + Makefile glitch fix
darcs-hash:20070221135220-946c4-35e8a07b4eb8fba787a4ccf7ec072505ac752421.gz

diff --git a/src/classmail b/src/classmail
--- a/src/classmail
+++ b/src/classmail
@@ -147,10 +147,20 @@ studymail() {
     done
 }
 
+categories() {
+    (cd "$ConfigDir" && ls *.mailboxes 2>/dev/null | sed -e 's/.mailboxes$//')
+}
+# create default config if not exists
+[ -d "$ConfigDir" ] || mkdir -p "$ConfigDir" ||
+    { err "$ConfigDir: cannot prepare config directory"; exit 4; }
+[ -f "$ConfigDir" ] || touch "$ConfigDir/config" ||
+    { err "$ConfigDir: cannot prepare default config"; exit 4; }
+[ -n "`categories`" ] || touch "$ConfigDir"/{ham,spam}.mailboxes ||
+    { err "$ConfigDir: cannot prepare default categories"; }
 
 # read config
 . "$ConfigDir/config"
-Categories=`cd "$ConfigDir" && ls *.mailboxes | sed -e 's/.mailboxes$//'`
+Categories=`categories`
 
 # sanitize config
 if ! [ -x "$Base/class-$ClassMethod" ]; then
